'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FirstCalls

    '''<summary>
    '''ClientHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientHeader As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''addFirstCall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addFirstCall As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''CompanyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''FirstCallID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstCallID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ValidationSummaryFirstCall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummaryFirstCall As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''MsgScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgScriptManager As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''clientId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clientId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''clientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clientName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''msgDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''msgTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''msgDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgDateTime As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''reportingName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reportingName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqReportingName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqReportingName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''reportingPartyTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reportingPartyTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqRelationTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqRelationTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''reportingPartyPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reportingPartyPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''deceasedName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deceasedName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqDeceasedName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqDeceasedName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''dDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DateOfDeathValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateOfDeathValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''dTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegExValidatorTimeOfDeath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegExValidatorTimeOfDeath As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ssn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ssn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegExValidatorSSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegExValidatorSSN As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''dob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dob As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DOBValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOBValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''weight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents weight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegExWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegExWeight As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''placeOfDeath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents placeOfDeath As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''facilityAddr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents facilityAddr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''facTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents facTypes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''facCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents facCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''facState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents facState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqExFacState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqExFacState As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''facilityCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents facilityCounty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''facilityZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents facilityZip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqExFacZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqExFacZip As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''facilityPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents facilityPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqExFacPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqExFacPhone As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''areaOfDeathTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents areaOfDeathTypes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
  '''roomNumber control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents roomNumber As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
    '''partyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents partyName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''relationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents relationship As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''responsiblePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents responsiblePhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ReqResponibleParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReqResponibleParty As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RegExResponsibleParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegExResponsibleParty As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''responsibleAltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents responsibleAltPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''responsiblePhoneExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents responsiblePhoneExt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''authorizedPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents authorizedPerson As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''authorizedPersonRelationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents authorizedPersonRelationship As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''authorizedPersonRelationshipPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents authorizedPersonRelationshipPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''physicianName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents physicianName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''physicianPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents physicianPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegExPhysicianPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegExPhysicianPhone As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''physicianDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents physicianDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LastSawValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastSawValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''coronerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coronerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''caseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caseNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''counselorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents counselorName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''coronerDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coronerDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CoronerDateValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoronerDateValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''coronerTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coronerTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegExCoronerTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegExCoronerTime As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''specialInstructionsR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents specialInstructionsR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''operatorNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operatorNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RBMessageStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBMessageStatus As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''ValidatorStatusRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidatorStatusRadio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''submitMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitMessage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''facilityNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents facilityNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
  '''rpContacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
  Protected WithEvents rpContacts As Global.System.Web.UI.WebControls.Repeater
End Class
