'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class firstCall

  '''<summary>
  '''ClientHeader control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ClientHeader As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''addFirstCall control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents addFirstCall As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''CompanyID control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents CompanyID As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''FirstCallID control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FirstCallID As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''ValidationSummaryFirstCall control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummaryFirstCall As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''MsgScriptManager control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MsgScriptManager As Global.System.Web.UI.ScriptManager

  '''<summary>
  '''clientId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents clientId As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''clientName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents clientName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''msgDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents msgDate As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''msgTime control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents msgTime As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''msgDateTime control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents msgDateTime As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''reportingName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents reportingName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqReportingName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqReportingName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''deceasedName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents deceasedName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqDeceasedName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqDeceasedName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''dDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents dDate As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqDateOfDeath control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqDateOfDeath As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''DateOfDeathValidator control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents DateOfDeathValidator As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''dTime control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents dTime As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqTimeOfDeath control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqTimeOfDeath As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''RegExValidatorTimeOfDeath control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegExValidatorTimeOfDeath As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''ssn control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ssn As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqSSN control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqSSN As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''RegExValidatorSSN control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegExValidatorSSN As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''dob control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents dob As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqDOB control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqDOB As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''DOBValidator control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents DOBValidator As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''weight control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents weight As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqWeight control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqWeight As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''placeOfDeath control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents placeOfDeath As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqPlaceOfDeath control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqPlaceOfDeath As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''facilityAddr control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityAddr As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacAddr control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacAddr As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''facType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facType As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''facCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facCity As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''facState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facState As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacState As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ReqExFacState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqExFacState As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''facilityCounty control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityCounty As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacCounty control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacCounty As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''facilityZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityZip As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacZip As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ReqExFacZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqExFacZip As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''facilityPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ReqExFacPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqExFacPhone As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''phoneExt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phoneExt As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''partyName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents partyName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqPartyName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqPartyName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''relationship control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents relationship As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ReqRelationship control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqRelationship As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''responsiblePhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents responsiblePhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqResponibleParty control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqResponibleParty As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''RegExResponsibleParty control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegExResponsibleParty As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''responsiblePhoneExt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents responsiblePhoneExt As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''physicianName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqPhysicianName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqPhysicianName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''physicianPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqPhysicianPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqPhysicianPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''RegExPhysicianPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegExPhysicianPhone As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''physicianPhoneExt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianPhoneExt As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''physicianDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianDate As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqPhysicianDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqPhysicianDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''LastSawValidator control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LastSawValidator As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''coronerName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents coronerName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqCoronerName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqCoronerName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''caseNumber control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents caseNumber As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqCaseNumber control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqCaseNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''counselorName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents counselorName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqCounselorName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqCounselorName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''coronerDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents coronerDate As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''CoronerDateValidator control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents CoronerDateValidator As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''ReqCoronerDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqCoronerDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''coronerTime control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents coronerTime As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqCoronerTime control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqCoronerTime As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''RegExCoronerTime control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegExCoronerTime As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''specialInstructionsR control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents specialInstructionsR As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''specialInstructionsA control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents specialInstructionsA As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''submitMessage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents submitMessage As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''FacilityNotesUpdate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FacilityNotesUpdate As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''facilityNotes control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityNotes As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''Button1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''operatorNotes control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents operatorNotes As Global.System.Web.UI.WebControls.TextBox
End Class
