'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Main

  '''<summary>
  '''MessageTable control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MessageTable As Global.System.Web.UI.HtmlControls.HtmlTable

  '''<summary>
  '''msgID control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents msgID As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''status control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents status As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''fCall control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents fCall As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''client control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents client As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''ClientTable control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ClientTable As Global.System.Web.UI.HtmlControls.HtmlTable

  '''<summary>
  '''clientID control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents clientID As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''clientName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents clientName As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''onCall control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents onCall As Global.System.Web.UI.HtmlControls.HtmlTableCell
End Class
