'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Messages

  '''<summary>
  '''clientMessageId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents clientMessageId As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''clientName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents clientName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''addMessage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents addMessage As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''MessageID control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MessageID As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''MsgScriptManager control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MsgScriptManager As Global.System.Web.UI.ScriptManager

  '''<summary>
  '''MsgTo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MsgTo As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqTo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqTo As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''MsgFrom control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MsgFrom As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFrom control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFrom As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nMsgPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nMsgPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nMsgPhoneX control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nMsgPhoneX As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''nMsgAlt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nMsgAlt As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqAltPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqAltPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nMsgAltX control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nMsgAltX As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''QwkMessage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents QwkMessage As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ReqQwkMessage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqQwkMessage As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''Message control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Message As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqMessage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqMessage As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''Notes control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Notes As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''submitMessage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents submitMessage As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''clientMainInfo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents clientMainInfo As Global.System.Web.UI.HtmlControls.HtmlTextArea
End Class
