'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddClient

  '''<summary>
  '''addNewClient control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents addNewClient As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''MsgScriptManager control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MsgScriptManager As Global.System.Web.UI.ScriptManager

  '''<summary>
  '''ClientIDText control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ClientIDText As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnTriggerUpdatePanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnTriggerUpdatePanel As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''ContactUpdatePanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ContactUpdatePanel As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''grvContacts control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents grvContacts As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''hContactID control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hContactID As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''ddContactType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddContactType As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ReqContactType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqContactType As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nContactName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nContactName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqContactName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqContactName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nContactJobTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nContactJobTitle As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqContactJobTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqContactJobTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nContactPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nContactPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqContactPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqContactPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nContactEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nContactEmail As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''nContactAdditionalInformation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nContactAdditionalInformation As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''resetContactSession control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents resetContactSession As Global.System.Web.UI.HtmlControls.HtmlInputHidden

  '''<summary>
  '''ClearContact control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ClearContact As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''SubmitContact control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SubmitContact As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''ValidationSummaryAddClient control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummaryAddClient As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''ValidationSummaryContact control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummaryContact As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''nClientName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ClientType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ClientType As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ReqClientType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientType As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nClientNumber control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientNumber As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientNumber control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nClientAddress control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientAddress As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientAddress control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nClientCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientCity As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nClientState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientState As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientState As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nClientZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientZip As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientZip As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nClientPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nClientPhone2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientPhone2 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqPhone2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqPhone2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nClientFax control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientFax As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientFax control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientFax As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nBackline1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nBackline1 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''nBackline2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nBackline2 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''nClientGreeting control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientGreeting As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientGreeting control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientGreeting As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nClientHours control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientHours As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientHours control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientHours As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''nClientAdditionalInformation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientAdditionalInformation As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''nClientSpecialInstructions control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents nClientSpecialInstructions As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqClientSpecialInstructions control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqClientSpecialInstructions As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''clientId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents clientId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

  '''<summary>
  '''resetForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents resetForm As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''SubmitClient control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SubmitClient As Global.System.Web.UI.WebControls.Button
End Class
