'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddFacility

  '''<summary>
  '''addNewFacility control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents addNewFacility As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''facilityName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''facilityType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityType As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''facilityAddress control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityAddress As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''facilityCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityCity As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''facilityState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityState As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''facilityZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityZip As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''facilityPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''facilityExt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityExt As Global.System.Web.UI.WebControls.TextBox
End Class
