'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddFacility

  '''<summary>
  '''addNewFacility control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents addNewFacility As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''placeOfDeath control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents placeOfDeath As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqPlaceOfDeath control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqPlaceOfDeath As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''facilityAddr control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityAddr As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacAddr control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacAddr As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''facType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facType As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''facCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facCity As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''facState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facState As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacState As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ReqExFacState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqExFacState As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''facilityCounty control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityCounty As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacCounty control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacCounty As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''facilityZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityZip As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacZip As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ReqExFacZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqExFacZip As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''facilityPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqFacPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqFacPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ReqExFacPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqExFacPhone As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''phoneExt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phoneExt As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''facilityId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents facilityId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

  '''<summary>
  '''SubmitFacility control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SubmitFacility As Global.System.Web.UI.WebControls.Button
End Class
