'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddPhysician

  '''<summary>
  '''addNewPhysician control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents addNewPhysician As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''AddPhysicianValidationSummary control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents AddPhysicianValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''physicianName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqPhysicianName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqPhysicianName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''physicianPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqPhysicianPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqPhysicianPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''RegExPhysicianPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegExPhysicianPhone As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''physicianPhoneExt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianPhoneExt As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''physicianId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

  '''<summary>
  '''SubmitPhysician control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SubmitPhysician As Global.System.Web.UI.WebControls.Button
End Class
