'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddPhysician

  '''<summary>
  '''PhysiciansTable control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PhysiciansTable As Global.System.Web.UI.HtmlControls.HtmlTable

  '''<summary>
  '''pName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pName As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''pPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pPhone As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''pExt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pExt As Global.System.Web.UI.HtmlControls.HtmlTableCell

  '''<summary>
  '''addNewPhysician control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents addNewPhysician As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''physicianFname control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianFname As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''physicianLname control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianLname As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''physicianPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''physicianExt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents physicianExt As Global.System.Web.UI.WebControls.TextBox
End Class
